### ISSUE TITLE
Seems like pip install error?

### ISSUE THREAD

**Issue by alicelayouttkl** [owenwijaya22/mail-automation#1]
Hi i tried to use the library by installing it through pip but i encountered some errors. Am I supposed to install it through chocolatey?

**Comment by owenwijaya22** [comment]
Hey, lemme try

**Comment by owenwijaya22** [comment]
Oh I didn't find any error just know, ran on Ubuntu!

**Comment by alicelayouttkl** [comment]
fr? i hv no idea why it doesn't work on my laptop

**Comment by owenwijaya22** [comment]
try clearing proxy first if u r using school wifi

**Comment by alicelayouttkl** [comment]
damn, thanks a lot!

**Comment by owenwijaya22** [comment]
np, it worked right?
